### ISSUE TITLE
GL backend todo

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#5]
- [x] apply-draw-state: state caching for vertex attribute definition
- [x] apply-draw-state: bind textures
- [x] extension check, sg_query_feature(), instancing functions
- [x] error codes and messages
- [x] _sg_create_shader: resolve uniform and texture locations (named and 'opaque')
- [x] create image
- [x] create pass
- [x] query default frame buffer at start
- [x] MRT passes
- [x] draw-elements-instanced
- [x] cleanup resources on shutdown
- [x] viewport and scissor rect functions are totally missing

**Comment by anael-seghezzi** [comment]
Hi, someone posted a request on CToy to be able to use sokol. The discussion seems to highlight the fact that SOKOL_GLES2 doesn't filter properly all non-opengl-es2 features.

More details here: https://github.com/anael-seghezzi/CToy/issues/5#issuecomment-320705048

**Comment by floooh** [comment]
Hi, thanks for the notification :) Sokol is still very work-in-progress, and as you noticed, the various GL backend variations for GL3.3, GLES2 and GLES3 are not properly separated yet.

I'll write a ticket to myself to clean this up, and I'll use my RaspberryPi to test the GLES2 backend (this has a very basic GLES2 implementation, I think if it works there it will work on any other GLES2 platform).

Cheers!
