### ISSUE TITLE
sokol_spine.h: todo list

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#709]
- [x] handle pre-multiplied alpha vs 'straight' alpha
- [x] merge draw commands
- [x] the API should not return pointers to internal string data (which might then go away at any time)
- [x] expose Spine events
- [x] the *_info structs should return the shared data items on the skeleton, not the per-instance items (this also means, the get_info functions take a skeleton handle, not an instance handle
- [x] the per-instance items are either access through granular getter functions or separate instance-info structs
- [x] iterate through triggered events
- [x] bone world-to-local and local-to-world transform
- [x] inspect and set IK targets
- [x] iterate and set skins
- [ ] ~~iterate and set attachments~~
- [x] try out new error handling ideas
- [x] documentation
- [x] 'simplest possible' sample
- [x] benchmark sample
- [x] draw layer sample (interleaved rendering with sokol_gl.h?)
- [x] context sample (render to offscreen render targets)
- [x] fix all the GH Action problems (Windows, iOS, Linux - Emscripten problem is unrelated to sokol_spine.h)

...ok, the iOS GH Actions problem is also fixed on the master branch. Ready for merge...

edit: erm not quite, documentation is still missing a few bits and pieces...
